# Generated by Django 5.2 on 2025-04-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=110)),
                ('desc_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('image', models.URLField(max_length=500)),
            ],
        ),
    ]
